#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use SymfonyBundler\App;

$app = new App();

$app->registerController('create', new \App\Command\CreateController($app));

$app->registerCommand('help', function (array $argv) use ($app) {
    $logo = 
    "\033[33m
    _____                     __                       ____                     _  _             
    / ____|                   / _|                     |  _ \                   | || |            
   | (___   _   _  _ __ ___  | |_  ___   _ __   _   _  | |_) | _   _  _ __    __| || |  ___  _ __ 
    \___ \ | | | || '_ ` _ \ |  _|/ _ \ | '_ \ | | | | |  _ < | | | || '_ \  / _` || | / _ \| '__|
    ____) || |_| || | | | | || | | (_) || | | || |_| | | |_) || |_| || | | || (_| || ||  __/| |   
   |_____/  \__, ||_| |_| |_||_|  \___/ |_| |_| \__, | |____/  \__,_||_| |_| \__,_||_| \___||_|   
             __/ |                               __/ |                                            
            |___/                               |___/                                             
      
    ";
    $app->getPrinter()->display($logo);
    $app->getPrinter()->display("usage: symfonybundler create <directory> <bundle-name>");
});

$app->runCommand($argv);
